# .github/workflows/trigger-doc-gen.yml
name: Trigger iFlow Doc Generation

on:
  push:
    branches:
      - main
    paths:
      - 'IntegrationFlows/UnZip/TEST_01/src/main/resources/scenarioflows/integrationflow/**'

jobs:
  notify-python-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Python Repo Workflow via Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PYTHON_REPO_TOKEN }}
          repository: Vanam-Srija/Doc_Generating_Code
          event-type: generate-iflow-docs
